### ISSUE TITLE
We will remember!

### ISSUE THREAD

**Issue by Bishwas-py** [TheBinitGhimire/TheBinitGhimire#3]
You were a huge inspiration to me!

**Comment by prolaxu** [comment]
lose a great talent

**Comment by sachinpantha** [comment]
You were so extra ordinary and a boon to Cybersecurity field!

**Comment by asujan205** [comment]
sad to heard rip bro

**Comment by aabishkaryal** [comment]
Even though we have not talked much, You were such a huge inspiration to me and the community. We will always miss you.

**Comment by Anmol2059** [comment]
Knew Binit since 2015 , he was a fun guy, a talented person, an inspiration indeed.

**Comment by Roshankandel** [comment]
He was the great inspiration, We will always miss you.

**Comment by Bishwas-py** [comment]
I have never talked to him personally, but his activities fascinated me, and pushed me to do a little more

**Comment by heissarad** [comment]
I was shocked to hear the news we lost the gem RIP.

**Comment by amit-timalsina** [comment]
> I have never talked to him personally, but his activities fascinated me, and pushed me to do a little more

Same here
